package arrayoperations;

import java.util.Random;

public class ArrayOperations {

    public static void main(String[] args) {
        Random RNG = new Random();

//create an array of ints with a size 10,000
        int[] cluster = new int[10000];

//Fill the array with random numbers between 0 - 200 generated by Random() above.
        for (int counter1 = 0; counter1 < cluster.length; counter1++) {

            cluster[counter1] = RNG.nextInt(201);

        }
        /*To get the sum we need to do a for loop that stops at the end of the array length
         it adds every number along the way in my variable sum then it divides the sum
         by 10,000 to get the average.
         */
        int sum = 0;
        for (int i : cluster) {
            sum += i;
        }
        System.out.println("Sum     =  " + sum);
        System.out.println("Average = " + sum / 10000);

        /*
         Min value with index here
         */
        int minValue = cluster[0];
        for (int i = 0; i < cluster.length; i++) {
            if (cluster[i] < minValue) {
                minValue = cluster[i];

            }

        }
        int minIndex = 0;
        for (int x = 0; x < cluster.length; x++) {
            int newNumber = cluster[x];
            if ((newNumber < cluster[minIndex])) {
                minIndex = x;

            }

        }
        System.out.println("Minimum = " + minValue + " and its index is " + minIndex);
        /*
         Max value with index here
         */
        int maxValue = cluster[0];
        for (int i = 0; i < cluster.length; i++) {
            if (cluster[i] > maxValue) {
                maxValue = cluster[i];
            }
        }
        int maxIndex = 0;
        for (int i = 0; i < cluster.length; i++) {
            int newnumber = cluster[i];
            if ((newnumber > cluster[maxIndex])) {
                maxIndex = i;

            }
        }
        System.out.println("Maximum = " + maxValue + " and its index is " + maxIndex);

//Count even and odd numbers
        int oddCount = 0;
        int evenCount = 0;
        for (int i = 0; i < cluster.length; i++) {
            if (cluster[i] % 2 == 0) {
                evenCount++;
            } else {
                oddCount++;
            }
        }
        System.out.println("The array has " + oddCount + " odd numbers");
        System.out.println("The array has " + evenCount + " even numbers");
//The sum of even and odd numbers separately
        int evenSum = 0;
        int oddSum = 0;
        for (int i : cluster) {
            if (i % 2 != 0) {
                evenSum += i;
            } else {
                oddSum += i;
            }

        }
        System.out.println("The sum of even numbers = " + evenSum);
        System.out.println("The sum of odd numbers = " + oddSum);

    }

}
